# Generated by Django 6.0.6 on 2026-07-13 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0008_securitymessage_organization'),
        ('responsibilities', '0002_rename_responsibilitytag_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsibility',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='responsibilities', to='mainsite.organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainsite.organization'),
            preserve_default=False,
        ),
    ]
