# Generated by Django 6.0.6 on 2026-07-23 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('responsibilities', '0003_responsibility_organization_tag_organization'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['pk']},
        ),
    ]
