# Generated by Django 6.0.6 on 2026-06-30 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0065_prform_organization'),
        ('workflows', '0033_employeetransition_extension_remain_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowinstance',
            name='cancellation_reason',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='workflowinstance',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_workflow_instances', to='people.employee'),
        ),
    ]
