# Generated by Django 6.0.6 on 2026-07-02 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0033_employeetransition_extension_remain_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowinstance',
            name='cancelation_reason',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='workflowinstance',
            name='canceled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canceled_workflow_instances', to='people.employee'),
        ),
    ]
