# Generated by Django 6.0.6 on 2026-07-17 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0034_workflowinstance_cancelation_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeetransition',
            name='assignee',
            field=models.CharField(choices=[('None', 'None'), ('Submitter', 'Submitter'), ('Fiscal', 'Fiscal'), ('HR', 'HR'), ('Complete', 'Complete')], default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='employeetransition',
            name='union_affiliation',
            field=models.CharField(blank=True, choices=[('Non-Represented', 'Non-Represented'), ('EA', 'EA'), ('SEIU', 'SEIU'), ('Senior Meals', 'Senior Meals'), ('Management', 'Management'), ('GSAM', 'GSAM'), ('SDSMC', 'SDSMC')], max_length=20),
        ),
    ]
