# Generated by Django 6.0.6 on 2026-07-21 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0008_securitymessage_organization'),
        ('workflows', '0035_alter_employeetransition_assignee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_actions', to='mainsite.organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeetransition',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='employee_transitions', to='mainsite.organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='process',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_processes', to='mainsite.organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='processinstance',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_process_instances', to='mainsite.organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='role',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_roles', to='mainsite.organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='step',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_steps', to='mainsite.organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stepchoice',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_step_choices', to='mainsite.organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stepinstance',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_step_instances', to='mainsite.organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workflow',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='mainsite.organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workflowinstance',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_instances', to='mainsite.organization'),
            preserve_default=False,
        ),
    ]
