# Generated by Django 6.0.6 on 2026-07-23 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0036_action_organization_employeetransition_organization_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='process',
            options={'ordering': ['pk'], 'verbose_name_plural': 'Processes'},
        ),
        migrations.AlterModelOptions(
            name='step',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='stepchoice',
            options={'ordering': ['pk']},
        ),
    ]
