# Generated by Django 6.0.4 on 2026-05-27 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phish', '0006_phishconfiguration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phishreport',
            name='status',
            field=models.CharField(choices=[('reported', 'Reported'), ('phish', 'Phish'), ('not_phish', 'Not Phish'), ('training', 'Training Needed')], default='reported', max_length=255),
        ),
    ]
