# Generated by Django 6.0.6 on 2026-06-25 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0008_securitymessage_organization'),
        ('people', '0065_prform_organization'),
        ('phish', '0007_alter_phishreport_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhishGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('color', models.CharField(default='primary', max_length=32)),
                ('members', models.ManyToManyField(blank=True, related_name='phish_groups', to='people.employee')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phish_groups', to='mainsite.organization')),
            ],
            options={
                'verbose_name': 'Phish Group',
                'verbose_name_plural': 'Phish Groups',
            },
        ),
        migrations.CreateModel(
            name='PhishRiskProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('color', models.CharField(default='primary', max_length=32)),
                ('members', models.ManyToManyField(blank=True, related_name='phish_risk_profiles', to='people.employee')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phish_risk_profiles', to='mainsite.organization')),
            ],
            options={
                'verbose_name': 'Phish Risk Profile',
                'verbose_name_plural': 'Phish Risk Profiles',
            },
        ),
    ]
