# Generated by Django 6.0.6 on 2026-07-23 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phish', '0008_phishgroup_phishriskprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='syntheticphishtemplate',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='trainingtemplate',
            options={'ordering': ['pk']},
        ),
    ]
