# Generated by Django 6.0.6 on 2026-08-19 23:07

import phish.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phish', '0009_alter_syntheticphishtemplate_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='syntheticphish',
            name='click_token',
            field=models.CharField(db_index=True, default=phish.models.generate_click_token, editable=False, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='syntheticphish',
            name='clicked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
