# Generated by Django 6.0.6 on 2026-08-19 23:07

from django.db import migrations
import phish.models


def gen_token(apps, schema_editor):
    SyntheticPhish = apps.get_model("phish", "SyntheticPhish")
    for row in SyntheticPhish.objects.all():
        row.click_token = phish.models.generate_click_token()
        row.save(update_fields=["click_token"])


class Migration(migrations.Migration):

    dependencies = [
        ('phish', '0010_syntheticphish_click_token_syntheticphish_clicked_at'),
    ]

    operations = [
        migrations.RunPython(gen_token, reverse_code=migrations.RunPython.noop),
    ]
