# Generated by Django 6.0.6 on 2026-08-19 23:07

from django.db import migrations, models
import phish.models


class Migration(migrations.Migration):

    dependencies = [
        ('phish', '0011_generate_syntheticphish_clicktoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syntheticphish',
            name='click_token',
            field=models.CharField(db_index=True, default=phish.models.generate_click_token, editable=False, max_length=64, unique=True),
        ),
    ]
