# Generated by Django 6.0.6 on 2026-08-20 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phish', '0012_remove_syntheticphish_clicktoken_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='phishconfiguration',
            name='phish_link_domain',
            field=models.CharField(blank=True, help_text='Domain used for synthetic phishing links. For example, "https://hu1Wei.s.gy" (no trailing slash).', max_length=255, null=True),
        ),
    ]
