# Generated by Django 6.0.6 on 2026-08-20 23:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phish', '0013_phishconfiguration_phish_link_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syntheticphishtemplate',
            name='body',
            field=ckeditor.fields.RichTextField(help_text="HTML content of the email. Use the following variables to personalize messages:<ul><li>{{user__email}} – user's email</li><li>{{user__first_name}} – user's first name</li><li>{{user__last_name}} – user's last name</li><li>{{user__name}} – user's full name</li><li>{{org__name}} – organization's name</li><li>{{click_url}} – link which tracks user clicks - configured in your Organization's Phish Configuration</li></ul>"),
        ),
    ]
