# Generated by Django 6.1 on 2026-08-27 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phish', '0014_alter_syntheticphishtemplate_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='syntheticphishtemplate',
            name='failure_message',
            field=models.TextField(blank=True, help_text="Message displayed when the user clicks a phishing link and fails the simulation, providing feedback to the user. For example, 'The message contained a suspicious link.' or 'Your manager will never email you asking for your Social Security number.'", null=True),
        ),
    ]
