# Generated by Django 6.1 on 2026-08-28 23:49

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phish', '0015_syntheticphishtemplate_failure_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syntheticphishtemplate',
            name='body',
            field=ckeditor.fields.RichTextField(help_text="HTML content of the email. Use the following variables to personalize messages:<ul><li>{{user_email}} – user's email</li><li>{{user_first_name}} – user's first name</li><li>{{user_last_name}} – user's last name</li><li>{{user_name}} – user's full name</li><li>{{org_name}} – organization's name</li><li>{{click_url}} – link which tracks user clicks - configured in your Organization's Phish Configuration</li></ul>"),
        ),
    ]
