# Generated by Django 6.1 on 2026-10-07 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phish', '0017_phishreport_has_attachments_phishreport_sender_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phishreportattachment',
            old_name='attachments',
            new_name='attachment',
        ),
        migrations.AddField(
            model_name='phishreportattachment',
            name='filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
