# Generated by Django 6.0.6 on 2026-07-21 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0008_securitymessage_organization'),
        ('purchases', '0012_expensemonth_approved_as_of_expensemonth_denier_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='mainsite.organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expensecard',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='expense_cards', to='mainsite.organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expensemonth',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='mainsite.organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expensemonthlock',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='expense_month_locks', to='mainsite.organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expensestatement',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='expense_statements', to='mainsite.organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='role',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainsite.organization'),
            preserve_default=False,
        ),
    ]
