# Generated by Django 6.0.6 on 2026-07-07 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0065_prform_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowoptions',
            name='column_sort',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
