# Generated by Django 6.0.6 on 2026-07-10 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0066_workflowoptions_column_sort'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email_opt_out_phish_all',
            field=models.BooleanField(default=False),
        ),
    ]
