# Generated by Django 6.0.6 on 2026-07-13 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0008_securitymessage_organization'),
        ('people', '0067_employee_email_opt_out_phish_all'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobtitle',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainsite.organization'),
            preserve_default=False,
        ),
    ]
