# Generated by Django 6.0.6 on 2026-07-23 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0068_jobtitle_organization'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='signature',
            options={'ordering': ['-pk'], 'verbose_name': 'PR Signature', 'verbose_name_plural': 'PR Signatures'},
        ),
        migrations.AlterModelOptions(
            name='teleworksignature',
            options={'ordering': ['-pk'], 'verbose_name': 'Telework Signature', 'verbose_name_plural': 'Telework Signatures'},
        ),
        migrations.AlterModelOptions(
            name='viewedsecuritymessage',
            options={'ordering': ['-datetime'], 'verbose_name': 'Viewed Security Message', 'verbose_name_plural': 'Viewed Security Messages'},
        ),
        migrations.AlterModelOptions(
            name='workflowoptions',
            options={'ordering': ['pk'], 'verbose_name': 'Workflow Option', 'verbose_name_plural': 'Workflow Options'},
        ),
    ]
