# Generated by Django 6.1 on 2026-10-02 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0009_module_organization_modules'),
        ('people', '0069_alter_signature_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('members', models.ManyToManyField(blank=True, related_name='review_roles', to='people.employee')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_roles', to='mainsite.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
